version: '3.8'

services:
  app:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: clinic
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  db_data:
